### ISSUE TITLE
ShowGroundItemPacketEncoder

### ISSUE THREAD

**Issue by RenatoJimenezDev** [nshusa/kotlin-osrs#4]
Packet 20 is set item on widget, show ground item is packet 187

Packet 20 consists of: 
    widget hash: LEInt
    item id: LEShort
    amount: LEInt

**Comment by nshusa** [comment]
```java
                                if (staticInt189 == 187) {
                                    i_30 = staticPacket3.readUShortA();
                                    i_2 = staticPacket3.readUShort();
                                    i_31 = staticPacket3.readUByteA();
                                    i_32 = WorldMapTile.staticInt5 + (i_31 >> 4 & 0x7);
                                    i_5 = Actor.staticInt318 + (i_31 & 0x7);
                                    if (i_32 >= 0 && i_5 >= 0 && i_32 < 104 && i_5 < 104) {
                                        item_35 = new Item();
                                        item_35.int657 = i_30;
                                        item_35.int658 = i_2;
                                        if (staticDequeArrayArrayArray1[DataClass14.staticInt156][i_32][i_5] == null)
                                            staticDequeArrayArrayArray1[DataClass14.staticInt156][i_32][i_5] = new Deque();

                                        staticDequeArrayArrayArray1[DataClass14.staticInt156][i_32][i_5].method253(item_35);
                                        staticMethod304(i_32, i_5);
                                    }

                                }
```
happen to know what this value is?
```java
WorldMapTile.staticInt5
```

**Comment by RenatoJimenezDev** [comment]
if (packetId == 187) {
                                    // spawn ground item
                                    int itemId = gameBuffer.readUShortA();
                                    int itemAmount = gameBuffer.readUShort();
                                    int tile = gameBuffer.readUByteA();
                                    int x = WorldMapTile.mapPacketBaseX + (tile >> 4 & 0x7);
                                    int z = Actor.mapPacketBaseZ + (tile & 0x7);
                                    if (x >= 0 && z >= 0 && x < 104 && z < 104) {
                                        Item groundItem = new Item();
                                        groundItem.itemId = itemId;
                                        groundItem.amount = itemAmount;
                                        if (groundItems[DataClass14.sceneHeight][x][z] == null)
                                            groundItems[DataClass14.sceneHeight][x][z] = new Deque();

                                        groundItems[DataClass14.sceneHeight][x][z].insertFront(groundItem);
                                        setGroundItem(x, z);
                                    }

                                }

**Comment by nshusa** [comment]
@RenatoJimenezDev Those are regional coordinates for anyone else looking at this. Also how is baseX calculated because I only see its set in 3 packets.

109
126
104

**Comment by RenatoJimenezDev** [comment]
You need to send packet 109 first before sending the ground item, that sets the baseX and baseZ

**Comment by nshusa** [comment]
@RenatoJimenezDev Alright, so then it's still the same as it was in 317 then.

```java
i_31 = staticPacket3.readUByteA();
```

you can send this as a zero and 109 will just set its position. What do you think a good name for packet 109 is? SetRegionUpdate? SetRegionCoordinates?

**Comment by RenatoJimenezDev** [comment]
Yeah I stuck to doing it by sending the MapBase (also what I named the out packet, SetMapBase) 

[https://i.imgur.com/ii5395i.png](url)
